receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Send to Jaeger (OTLP/HTTP on 4318)
  otlphttp:
    endpoint: http://jaeger:4318

  # Write spans to a mounted file in JSON lines (NDJSON) format
  file:
    path: /captures/capture_001.ndjson
    format: json
    rotation:
      max_megabytes: 100
      max_days: 3

  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, file, logging]
